package com.moneyfi.constants.enums;

public enum NotificationQueueEnum {
    USER_FEEDBACK_MAIL,
    USER_DEFECT_STATUS_MAIL,
    FORGOT_USERNAME_REQUEST_MAIL,
    USER_RAISED_DEFECT_TO_ADMIN_MAIL,
    SEND_REFERENCE_NUMBER_TO_USER_MAIL,
    SEND_USER_REQUEST_TO_INCREASE_GMAIL_SYNC_COUNT_TO_ADMIN_MAIL,
    ACCOUNT_STATEMENT_EMAIL,
    SPENDING_ANALYSIS_EMAIL,
    ADMIN_BLOCKED_USER_MAIL,
    GMAIL_SYNC_APPROVED_USER_MAIL,
    GMAIL_SYNC_REJECTED_USER_MAIL,
    CONTACT_US_HELP_CENTER_MAIL,
    NAME_CHANGE_REQUEST_APPROVED_MAIL,
    NAME_CHANGE_REQUEST_REJECTED_MAIL,
    USER_ACCOUNT_UNBLOCK_REQUEST_SUCCESSFUL_MAIL,
    USER_ACCOUNT_UNBLOCK_REQUEST_REJECTED_MAIL,
    USER_ACCOUNT_RETRIEVAL_REQUEST_SUCCESSFUL_MAIL,
    USER_ACCOUNT_RETRIEVAL_REQUEST_REJECTED_MAIL,
    USER_PASSWORD_CHANGE_ALERT_MAIL,
    OTP_MAIL_FOR_USER_SIGNUP,
    OTP_FOR_USER_BLOCK,
    OTP_FOR_FORGOT_PASSWORD,
    USER_ANNIVERSARY_MAIL,
    USER_BIRTHDAY_MAIL;
}
